### ISSUE TITLE
About low-frequency pictures  and shot

### ISSUE THREAD

**Issue by 18360939479** [tancik/StegaStamp#10]
Watermark steganography is bad for low-frequency pictures. Is it because my parameters have not been adjusted? When I deal with black-and-white document images, the visual effect of watermarks is very poor. How to adjust? The watermark cannot be extracted from the picture taken by the mobile phone.

**Comment by tancik** [comment]
I would recommend retraining the network using input images that have similar characteristics to the images you plan on testing with. You may need to tweak some of the hyperparameters to further improve the results. Additionally low frequency images are particularly hard to hide images into as the codes are typically hidden in the textures and edges in the image. To help visualize this, think about how you would hide a code in lowest frequency image possible (a flat color). Any modification would be very visible.
