### ISSUE TITLE
problem about the STN module

### ISSUE THREAD

**Issue by jj199603** [tancik/StegaStamp#18]
Hi,did you do the ablation study of the STN module of the decoder? I find it doesn't play an important role for improving decoding accuracy. Furthermore, the parameters of the STN cost too much space. The model size decrease from 200M to 50M after removing this module.

**Comment by tancik** [comment]
We did not specifically ablate the STN module. We found performance improvements when we first added the STN module early in the development cycle. It is possible that later modifications canceled out any gains provided by STN. If so, this is a great finding as the network can be lighter weight. Thanks for running these experiments!

**Comment by zimenglan-sysu-512** [comment]
@jj199603 
if remove the STN module, the decoder will degrade the performance?

**Comment by jj199603** [comment]
> @jj199603
> if remove the STN module, the decoder will degrade the performance?

We didn't find obvious degradation of the decoder performance. Because the author uses the inverse of the transormation matrix to the encoded image before feeding it to the decoder. We think that the geomatric distortion has been removed by this inverse matrix.

**Comment by jj199603** [comment]
> @jj199603
> if remove the STN module, the decoder will degrade the performance?

In real application, we found localization algorithm is very important to the decoder.
