### ISSUE TITLE
bitflips always has value -1

### ISSUE THREAD

**Issue by Jackqu** [tancik/StegaStamp#2]
When I run the code to my own video
python detector.py \
  --detector_model detector_models/stegastamp_detector \
  --decoder_model saved_models/stegastamp_pretrained \
  --video test_vid.mp4
I found bitflips always has value -1
The following is what I did：
step 1: Hide message into image lena and verified the message can be decoded
step 2: Print the image with message inside
step 3: Record a video of the printed image
And then, I found the bitflips always has value -1, could you help me with this problem. Thank you.
The image and video can be find here.[https://drive.google.com/open?id=1XGXWCN78kDvr6IEtTyIQKB6JJ9jXvTok]

**Comment by tancik** [comment]
Thanks for sharing the video to help with debugging. The code assumed the input was a horizontal video with dimensions 1920x1080. I updated to code to work with variable input sizes, your video will now work.

I also added a flag to the detector `--visualize_detector` which you can use to see raw output to the detector network. You will notice that this network has not been fully optimized, the detection can be rather noisy (particularly when the stegastamp is very large or small), when it does find the object, the decoder often does a pretty good job. I also noticed your video is only 960x540, one way to get better results will be to use an HD camera.
