### ISSUE TITLE
Output size

### ISSUE THREAD

**Issue by edwardocano** [tancik/StegaStamp#23]
The ouuout images are 400x400. IS possible to change this output to a higher quality?

**Comment by tancik** [comment]
400x400 is currently hardcoded into the code. You would need to update the value [here](https://github.com/tancik/StegaStamp/blob/de4e8ca27ad3cef5eabbe9d892fd6efa6eeced83/train.py#L95). Increasing the image size would increase the network's memory footprint and may be difficult to fit on the GPU. You would probably want to modify the network architecture to downscale more rapidly. Alternatively you could try outputting just the 400x400 residual and overlaying it onto the original high res image.

**Comment by edwardocano** [comment]
Thanks for your help!. 
Is possible to modify the effect of the mark on the imag?, because the distortion is very high. I have been trying merging the original image and the output image and with 30% of the original image i still can recover the ID. But i would like to do this from the neural network. (I am not printing the image, i just want that ID persist in atacks like JPEG, crops, and adding filters like instagram filters. )
I want re-traing the neural network what hardware did you use? and how many hours was trained?

**Comment by tancik** [comment]
It should take ~12 hours to train with a 1080Ti or equivalent GPU.

**Comment by edwardocano** [comment]
Thanks!.
