### ISSUE TITLE
Encode messages of different lengths.

### ISSUE THREAD

**Issue by edwardocano** [tancik/StegaStamp#24]
Where can i change the length of the message.

**Comment by tancik** [comment]
You can change the message length with the argument `--secret_size`

**Comment by edwardocano** [comment]
Thanks!, i have been trying to re-train in spite of i install al the requirements for cuda the training just run in the cpu. Is there any configuration for GPU?

**Comment by tancik** [comment]
All of the code is designed to run on GPU (we have never trained on CPU). Likely your tensorflow installation isn't finding your GPU.
