### ISSUE TITLE
 if this is an unexpected mistake in writing？

### ISSUE THREAD

**Issue by LeeeLiu** [tancik/StegaStamp#28]
Hello,  tancik
I wonder if this is  an unexpected mistake in writing？
"Accounting for error correcting, using only 50 total message bits would drastically reduce the number of possible encoded hyperlinks to under one billion"

The paper said that ”use 100 bits to hide 56 bits“,
so  if  we  use  50  bits,  it can hide ” under one billion“ ？ really？

look forward to your reply.  Many Thanks！

**Comment by tancik** [comment]
Lets say we use ~1/2 of the bits for error correction. If we start with 50 bits, then our message would be ~25 bits. 2^25 ~= 30 million which is < 1 billion.

**Comment by LeeeLiu** [comment]
> Lets say we use ~1/2 of the bits for error correction. If we start with 50 bits, then our message would be ~25 bits. 2^25 ~= 30 million which is < 1 billion.

Oh, I get it. 
Thank you for your prompt reply！
