### ISSUE TITLE
How high can  ‘bit_acc’  reach  without BCH code？

### ISSUE THREAD

**Issue by LeeeLiu** [tancik/StegaStamp#31]
Hello, tancik!

1. Excuse me, if you don't use BCH code, what is the decoding accuracy (bit_acc)?

2. Every 12 bytes (96 bits), only 5 bits can be corrected, right?
 - In `encode_image.py` and `decode_image.py`,  The BCH parameters you use are:
    ```
    BCH_POLYNOMIAL = 137
    BCH_BITS = 5
    ```
 - According to the `bchlib` source code, my understanding is,
 The entire packet can only be corrected by 5 bits, right?
 In your case, packet is 12 bytes (96 bits), data is 7 bytes (56 bits, embedded link length)

**Comment by tancik** [comment]
1. Table 1 of the paper has a breakdown of bit accuracy for different camera / printer pairs - https://arxiv.org/abs/1904.05343
2. Yep, you are correct.

**Comment by LeeeLiu** [comment]
Oh, I see.
Your reply is very helpful.
Thanks！


 
---Original---
