### ISSUE TITLE
can this model handle random size image input 

### ISSUE THREAD

**Issue by Hammer-888** [tancik/StegaStamp#33]
as title

**Comment by tancik** [comment]
The code is currently set up for 400x400px images. You would need to make modifications and retrain if you wanted to encode a different resolution.

**Comment by stephenivy07** [comment]
> The code is currently set up for 400x400px images. You would need to make modifications and retrain if you wanted to encode a different resolution.

Hi, I modified the code and wanted to retrain it on 256x256px images, but I met some problems. Could you please give me some guidance on how to train on images that are not 400x400px? Thank you so much!
![捕获](https://user-images.githubusercontent.com/34760100/119074760-2bb70080-ba22-11eb-8791-ff3800b7bbd0.PNG)

**Comment by fujiaixin09** [comment]
> 



> > The code is currently set up for 400x400px images. You would need to make modifications and retrain if you wanted to encode a different resolution.
> 
> Hi, I modified the code and wanted to retrain it on 256x256px images, but I met some problems. Could you please give me some guidance on how to train on images that are not 400x400px? Thank you so much!
> ![捕获](https://user-images.githubusercontent.com/34760100/119074760-2bb70080-ba22-11eb-8791-ff3800b7bbd0.PNG)

Because in coding, the author uses the u-net structure, and the left downsampling part is connected with the right upsampling part, so the dimension you entered is not correct.

**Comment by April4lu** [comment]
> > The code is currently set up for 400x400px images. You would need to make modifications and retrain if you wanted to encode a different resolution.
> 
> Hi, I modified the code and wanted to retrain it on 256x256px images, but I met some problems. Could you please give me some guidance on how to train on images that are not 400x400px? Thank you so much!
> ![捕获](https://user-images.githubusercontent.com/34760100/119074760-2bb70080-ba22-11eb-8791-ff3800b7bbd0.PNG)

I met the same error, did you solve this issue? I'll appreciate for your help!
