### ISSUE TITLE
The model size is extremely large T_T

### ISSUE THREAD

**Issue by 1165048017** [tancik/StegaStamp#4]
I trained the original model without any modification, and got a model which can work well. But the model size is too big, about 1.1GB, while the supplied pretrained model is 217MB.
I just wonder if the pretrained model has discard some weights? Like the discriminator network's weights?

**Comment by tancik** [comment]
Good catch. The large size was due to saving the optimizer variables. The code has been updated to only save constant values. The model size is now ~230mb,
