### ISSUE TITLE
Can't download trained models

### ISSUE THREAD

**Issue by amilcar** [tancik/StegaStamp#59]
First of all, great work @tancik and @bmild !!!
I recently discovered StegaStamp and was very impressed by the results you've shown in the paper and site. 
I'm trying to replicate your workflow, but got stuck in some problems:
I've tried to download the trained encoder and detector models following the instructions in README.md file, but I'm getting a 403 Forbidden response. 
Is there another way to obtain the trained models?
Thanks, in advance!

**Comment by GongYanfu** [comment]
I also meet this problem, is there a solution?

**Comment by tancik** [comment]
Unfortunately the university stopped hosting the models since I am no longer affiliated. I wasn't expecting this so I didn't think to download them ahead of time. As a result, I no longer have them. I have updated the Readme to avoid future confusion.

**Comment by V1lu0** [comment]
> I also meet this problem, is there a solution?

你找到了吗？我也需要

**Comment by GongYanfu** [comment]
no



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月11日 21:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) |

I also meet this problem, is there a solution?

你找到了吗？我也需要

**Comment by V1lu0** [comment]
> no
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年12月11日 21:40 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) | I also meet this problem, is there a solution? 你找到了吗？我也需要 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我可能找到了

**Comment by GongYanfu** [comment]
记得分享，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月11日 22:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) |

no
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年12月11日 21:40 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) | I also meet this problem, is there a solution? 你找到了吗？我也需要 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

我可能找到了

**Comment by amilcar** [comment]
Thanks for your attention, @tancik!

**Comment by GongYanfu** [comment]
> > no
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年12月11日 21:40 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) | I also meet this problem, is there a solution? 你找到了吗？我也需要 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我可能找到了

can you share it with us? thank you

**Comment by Map1e0823** [comment]
> > no
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年12月11日 21:40 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue #59) | I also meet this problem, is there a solution? 你找到了吗？我也需要 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我可能找到了

StegaStamp-Web？那个感觉效果没有论文里那么好啊

**Comment by ytfrdfiw** [comment]
> > > no
> > > […](#)
> > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年12月11日 21:40 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [tancik/StegaStamp] Can't download trained models (Issue [#59](https://github.com/tancik/StegaStamp/issues/59)) | I also meet this problem, is there a solution? 你找到了吗？我也需要 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 我可能找到了
> 
> can you share it with us? thank you

我下载到这个模型文件了，但是发现效果一般。我先嵌入水印，然后用手机拍照一张，提取手机的照片时，发现提取失败。但是通过QQ截图后的图片是可以提取的。如果你要的话，我发给你。
