### ISSUE TITLE
BCH initialization error

### ISSUE THREAD

**Issue by ruirui937** [tancik/StegaStamp#64]
Thank you to the author for introducing us to this remarkable research.  I would like to understand the basis for the settings ‘BCH_POLYNOMIAL = 137’ and ‘BCH_BITS = 5’.  However, when I execute 'bch = bchlib. BCH(BCH_POLYNOMIAL, BCH_BITS)' under the settings, I encounter the following error: 'RuntimeError: unable to initialize bch, invalid parameters?'. Could advice be provided on how to resolve this issue?

**Comment by YX-wal** [comment]
please do you have solved it? I'm having the same issue

**Comment by TrueRou** [comment]
> please do you have solved it? I'm having the same issue

resort the argument when initializing BCH object.

`bch = bchlib.BCH(BCH_BITS, BCH_POLYNOMIAL)`

**Comment by YX-wal** [comment]
> > 请问你解决了吗？我遇到了同样的问题
> 
> 在初始化 BCH 对象时重新调整参数。
> 
> `bch = bchlib.BCH(BCH_BITS, BCH_POLYNOMIAL)`

Swap this one direction `bch = bchlib.BCH(BCH_BITS, BCH_POLYNOMIAL)` to  `bch = bchlib.BCH(BCH_POLYNOMIAL,BCH_BITS)`
