### ISSUE TITLE
The theory of the random_blur_kernel function?

### ISSUE THREAD

**Issue by JisongXie** [tancik/StegaStamp#7]
Hi, I can't understand the motion blur kernel, which is implemented in[ random_blur_kernel function](https://github.com/tancik/StegaStamp/blob/2e852eeef967aa812f2d7ab79a7b55bd4ddd9c12/utils.py#L8).
https://github.com/tancik/StegaStamp/blob/2e852eeef967aa812f2d7ab79a7b55bd4ddd9c12/utils.py#L8
 Is there any paper or other materials which can help me understand it? It seems that it uses gauss function and makes a direction to simulate motion blur. I search Linear Motion Blur, and it's hard to find something related to this. Hope someone who know this can give me some references.

**Comment by tancik** [comment]
The motion blur implemented is just a heuristic for linear motion blur. Other more accurate implementation are possible. We use a randomly rotated 2D Gaussian kernel with randomly scaled components. In practice this looks like a bivariate normal density - https://en.wikipedia.org/wiki/Multivariate_normal_distribution

**Comment by SVithurabiman** [comment]
Hi @tancik , your work on StegaStamp is commendable. I am working on training your model and in this function it throws a `NotImplementedError: Cannot convert a symbolic Tensor (meshgrid/Size:0) to a numpy array.`  at line 10  `coords = tf.to_float(tf.stack(tf.meshgrid(tf.range(N_blur), tf.range(N_blur), indexing='ij'), -1)) - (.5 * (N-1))`. Any help with this would be appreciated.
