### ISSUE TITLE
Time problem of training model

### ISSUE THREAD

**Issue by 18360939479** [tancik/StegaStamp#8]
hello,if I have 10 pictures of 400X400, How long does it take for you to train the model. It took me a long time to train the model.

**Comment by tancik** [comment]
Training is based on the number of steps taken (default 140000) and thus is independent on the size of the dataset. Also I would recommend more than 10 images to avoid over fitting to those images.
In terms of time, it will depend on your GPU. With a 1080TI or equivalent GPU, I would expect it to take ~12hours. If you are finding that training is taking significantly longer, make sure that you are using CUDA.
