### ISSUE TITLE
Need Guidance to  implemented on camera scanning 

### ISSUE THREAD

**Issue by skynetindia** [tancik/StegaStamp#9]
Hi,

Thanks for this awesome library but can you please guide me how you have implemented this on the camera scanning 
If possible can you show some example code as when we are taking the images from the camera it doesn't work

**Comment by tancik** [comment]
Are you referring to mobile on device processing? If so, this is not currently possible as the GPU memory requirements are too large. Further optimization and development is needed for this capability.

**Comment by skynetindia** [comment]
Hi thanks for your reply
We are looking for something like digimarc where image encoding can be done on server section(similar to this library) but decoding on image can be done through the camera.
Do you have any idea how we can do it? It will be reply helpful to us

**Comment by tancik** [comment]
I am sorry, but that is not in scope for this project. We believe this is an excellent direction for future work.
